# Generated by Django 3.2.9 on 2021-11-04 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='n_players',
        ),
    ]
