# Generated by Django 3.2.9 on 2021-11-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0002_remove_game_n_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='pin',
        ),
        migrations.AlterField(
            model_name='game',
            name='round',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='turn',
            field=models.BooleanField(default=False),
        ),
    ]
