# Generated by Django 3.2.9 on 2021-11-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0003_auto_20211104_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(default='/static/default', upload_to=''),
        ),
    ]
