# Generated by Django 3.2.9 on 2021-12-06 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0004_game_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='category',
            new_name='category_id',
        ),
    ]
