# Generated by Django 3.2.9 on 2021-12-09 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0006_game_secret_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='image',
        ),
    ]
