# Generated by Django 3.2.9 on 2021-12-10 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0007_remove_game_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='secret_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='drawing.word'),
        ),
    ]
