# Generated by Django 3.2.9 on 2021-12-10 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0008_auto_20211210_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drawing.category'),
        ),
        migrations.AddField(
            model_name='game',
            name='first_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='second_points',
            field=models.IntegerField(default=0),
        ),
    ]
