# Generated by Django 3.2.9 on 2021-12-10 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0009_auto_20211210_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='secret_word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='drawing.word'),
        ),
    ]
